# Generated by Django 2.0.2 on 2018-02-13 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import viewflow.fields
import viewflow.token


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewflow', '0006_i18n'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_class', viewflow.fields.FlowReferenceField(max_length=250, verbose_name='Flow')),
                ('status', models.CharField(default='NEW', max_length=50, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Finished')),
                ('parent_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewflow.Process', verbose_name='ParentProcess')),
            ],
            options={
                'verbose_name': 'SubProcess',
                'verbose_name_plural': 'SubProcess list',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SubProcessTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_task', viewflow.fields.TaskReferenceField(max_length=255, verbose_name='Task')),
                ('flow_task_type', models.CharField(max_length=50, verbose_name='Type')),
                ('status', models.CharField(db_index=True, default='NEW', max_length=50, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('started', models.DateTimeField(blank=True, null=True, verbose_name='Started')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Finished')),
                ('token', viewflow.fields.TokenField(default=viewflow.token.Token('start'), max_length=150, verbose_name='Token')),
                ('external_task_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='External Task ID')),
                ('owner_permission', models.CharField(blank=True, max_length=255, null=True, verbose_name='Permission')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('previous', models.ManyToManyField(related_name='leading', to='viewflow.SubProcessTask', verbose_name='Previous')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewflow.SubProcess', verbose_name='SubProcess')),
            ],
            options={
                'verbose_name': 'SubProcessTask',
                'verbose_name_plural': 'SubprocessTasks',
                'ordering': ['-created'],
            },
        ),
    ]
